@extends('Dashboard.Configuration.master', ['title' => $title, 'description' => $description])
@extends('Dashboard.Configuration.Header.header')
@extends('Dashboard.Configuration.Header.Header-content.content')
@extends('Dashboard.Configuration.Header.Header-content.Left.left')
@extends('Dashboard.Configuration.Header.Header-content.Right.right')
@extends('Dashboard.Configuration.Header.Header-logo.logo')
@extends('Dashboard.Configuration.Header.Header-menu.menu')
@extends('Dashboard.Configuration.Header.Header-Mobile-menu.mobile-menu')
@extends('Dashboard.Configuration.Settings.app-settings')
@extends('Dashboard.Configuration.Sidebar.sidebar')
@extends('Dashboard.Configuration.Sidebar.Header.Logo')
@extends('Dashboard.Configuration.Sidebar.Header.menu')
@extends('Dashboard.Configuration.Sidebar.Header.mobile-menu')
@extends('Dashboard.Configuration.Scrollbar.scrollbar', ['page' => $page])
@extends('Dashboard.Configuration.Footer.Footer')
@extends('Dashboard.Configuration.Footer.Left')
@extends('Dashboard.Configuration.Footer.Right')