@extends('Dashboard.master', ['title' => $title, "description" => $description])
@extends('Dashboard.Header.header')
@extends('Dashboard.Header.Header-content.content')
@extends('Dashboard.Header.Header-content.Left.left')
@extends('Dashboard.Header.Header-content.Right.right')
@extends('Dashboard.Header.Header-logo.logo')
@extends('Dashboard.Header.Header-menu.menu')
@extends('Dashboard.Header.Header-Mobile-menu.mobile-menu')
@extends('Dashboard.Settings.app-settings')
@extends('Dashboard.Sidebar.sidebar')
@extends('Dashboard.Sidebar.Header.Logo')
@extends('Dashboard.Sidebar.Header.menu')
@extends('Dashboard.Sidebar.Header.mobile-menu')
@extends('Dashboard.scrollbar')
@extends('Dashboard.Footer.Footer')
@extends('Dashboard.Footer.Left')
@extends('Dashboard.Footer.Right')